module Haskell.Everything where

import Haskell.Prelude
import Haskell.Control.Monad
import Haskell.Law.List
import Haskell.Law.Bool
import Haskell.Law.Monoid.List
import Haskell.Law.Monoid.Def
import Haskell.Law.Monoid.Maybe
import Haskell.Law.Ord
import Haskell.Law.Monad.List
import Haskell.Law.Monad.IO
import Haskell.Law.Monad.Either
import Haskell.Law.Monad.Def
import Haskell.Law.Monad.Maybe
import Haskell.Law.Semigroup.List
import Haskell.Law.Semigroup.Either
import Haskell.Law.Semigroup.Def
import Haskell.Law.Semigroup.Maybe
import Haskell.Law.Equality
import Haskell.Law.Eq.Bool
import Haskell.Law.Eq.Def
import Haskell.Law.Eq.Maybe
import Haskell.Law.Eq.Ordering
import Haskell.Law.Monad
import Haskell.Law.Functor.List
import Haskell.Law.Functor.IO
import Haskell.Law.Functor.Either
import Haskell.Law.Functor.Def
import Haskell.Law.Functor.Maybe
import Haskell.Law.Applicative
import Haskell.Law.Ord.Bool
import Haskell.Law.Ord.Def
import Haskell.Law.Ord.Maybe
import Haskell.Law.Ord.Ordering
import Haskell.Law.Applicative.List
import Haskell.Law.Applicative.IO
import Haskell.Law.Applicative.Either
import Haskell.Law.Applicative.Def
import Haskell.Law.Applicative.Maybe
import Haskell.Law.Maybe
import Haskell.Law.Functor
import Haskell.Law.Monoid
import Haskell.Law.Eq
import Haskell.Law
import Haskell.Prim
import Haskell.Extra.Loop
import Haskell.Extra.Dec
import Haskell.Extra.Refinement
import Haskell.Extra.Erase
import Haskell.Prim.Double
import Haskell.Prim.Show
import Haskell.Prim.List
import Haskell.Prim.Int
import Haskell.Prim.Bool
import Haskell.Prim.Num
import Haskell.Prim.IO
import Haskell.Prim.Either
import Haskell.Prim.Ord
import Haskell.Prim.Word
import Haskell.Prim.Traversable
import Haskell.Prim.Integer
--import Haskell.Prim.Thunk
import Haskell.Prim.Absurd
import Haskell.Prim.String
import Haskell.Prim.Enum
import Haskell.Prim.Monad
import Haskell.Prim.Applicative
import Haskell.Prim.Maybe
import Haskell.Prim.Functor
import Haskell.Prim.Strict
import Haskell.Prim.Foldable
import Haskell.Prim.Tuple
import Haskell.Prim.Monoid
import Haskell.Prim.Bounded
import Haskell.Prim.Eq
